In [79]:
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [65]:
a = torch.FloatTensor(torch.zeros((3,4,5)))

In [66]:
a

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [67]:
# 2. Выведите его форму (shape)

In [68]:
a.shape

torch.Size([3, 4, 5])

In [69]:
# 3. Приведите его к форме 6х10

In [70]:
a = a.reshape(6,10)

In [71]:
# 4. Создайте случайный IntTensor размера 10

In [72]:
b = torch.randint(10,size=(10,))

In [73]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [74]:
 c = a*b
 c

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [76]:
torch.matmul(c,c.T)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [77]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [98]:
x = torch.tensor([1.0],requires_grad=True)
z = torch.tensor([0.5],requires_grad=True)
t = torch.tensor([2.0],requires_grad=True)

In [99]:
y = (x**3) + z - 75*t

In [100]:
y.backward(x,z,t)

In [102]:
x.grad, z.grad, t.grad

(tensor([3.], grad_fn=<CopyBackwards>),
 tensor([1.], grad_fn=<CopyBackwards>),
 tensor([-75.], grad_fn=<CopyBackwards>))

In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [116]:
n = torch.ones(5,6)
n

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 9. Переведите его в формат numpy

In [117]:
n.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)